# Generated by Django 5.0.7 on 2024-08-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='state',
            field=models.CharField(default='default_state', max_length=300),
        ),
    ]
